# docker-compose.yml
services:
  chat-legal-db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - chat_legal_network

  chat-legal-redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - chat_legal_network

  chat-legal-django:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    volumes:
      - ./staticfiles:/app/staticfiles  
      - ./media:/app/media    
    ports:
      - "8001:8000"  
    env_file:
      - .env  
    depends_on:
      - chat-legal-db
      - chat-legal-redis
    networks:
      - chat_legal_network

volumes:
  postgres_data:

networks:
  chat_legal_network:
