# Generated by Django 5.1.7 on 2025-04-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_legal', '0003_tokencost'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='token_cost',
            field=models.FloatField(default=0),
        ),
    ]
