# Generated by Django 5.1.7 on 2025-04-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_legal', '0004_state_token_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
