# Generated by Django 5.1.7 on 2025-04-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RagLegal',
        ),
    ]
